import type { EstimateItem, SubcontractorOrder } from "@/lib/types"

export const mockEstimateItems: EstimateItem[] = [
  {
    ID_EstimateItem: "EST50001",
    Category: "1000 - 1999 Preparation Preliminaries",
    Cost_Code: "1010 - Building permits",
    Title: "Permit Fees",
    Parent_Group: "Project/Permit Mgmt.",
    Parent_Group_Description: "",
    Subgroup: "",
    Subgroup_Description: "",
    Option_Type: "",
    Line_Item_Type: "Estimate",
    Description: "- This section covers the costs and procedures for obtaining the necessary permits for the project.",
    Quantity: 1.0,
    Unit: "",
    Unit_Cost: 800.0,
    Cost_Type: "Subcontractor",
    Marked_As: "",
    Builder_Cost: 800.0,
    Markup: 460.0,
    Markup_Type: "C/P",
    Unit_Price: 1260.0,
    Client_Price: 1260.0,
    Margin: 36.51,
    Profit: 460.0,
    Percent_Invoiced: 100.0,
    Internal_Notes: "",
    ID_Jobs: "PTL50001",
    ID_Order: "ORD50001",
  },
  {
    ID_EstimateItem: "EST50002",
    Category: "1000 - 1999 Preparation Preliminaries",
    Cost_Code: "1011 Supervision",
    Title: "Permit Mgmt",
    Parent_Group: "Project/Permit Mgmt.",
    Parent_Group_Description: "",
    Subgroup: "",
    Subgroup_Description: "",
    Option_Type: "",
    Line_Item_Type: "Estimate",
    Description:
      "Scope of Work - Permit management - this includes submissions, filing documents and scheduling inspections accordingly.",
    Quantity: 1.0,
    Unit: "",
    Unit_Cost: 0.0,
    Cost_Type: "Subcontractor",
    Marked_As: "",
    Builder_Cost: 0.0,
    Markup: 630.0,
    Markup_Type: "C/P",
    Unit_Price: 630.0,
    Client_Price: 630.0,
    Margin: 100.0,
    Profit: 630.0,
    Percent_Invoiced: 100.0,
    Internal_Notes: "",
    ID_Jobs: "PTL50001",
    ID_Order: "ORD50001",
  },
  {
    ID_EstimateItem: "EST50003",
    Category: "3000 - 3999 Rough Structure",
    Cost_Code: "3550 - Flatwork labor",
    Title: "Area Preparation",
    Parent_Group: "D12 Living/Dining Room",
    Parent_Group_Description: "",
    Subgroup: "",
    Subgroup_Description: "",
    Option_Type: "",
    Line_Item_Type: "Estimate",
    Description: "1. Masking & Prep for Paint: Plastic, paper, and tape are applied as needed to protect surfaces.",
    Quantity: 1.0,
    Unit: "",
    Unit_Cost: 80.0,
    Cost_Type: "Subcontractor",
    Marked_As: "",
    Builder_Cost: 80.0,
    Markup: 40.0,
    Markup_Type: "C/P",
    Unit_Price: 120.0,
    Client_Price: 120.0,
    Margin: 33.33,
    Profit: 40.0,
    Percent_Invoiced: 100.0,
    Internal_Notes: "",
    ID_Jobs: "PTL50001",
    ID_Order: "ORD50002",
  },
  {
    ID_EstimateItem: "EST50004",
    Category: "5000 - 5999 Finishing Trades",
    Cost_Code: "5100 - Drywall",
    Title: "Ceiling Repairs",
    Parent_Group: "D12 Bathroom",
    Parent_Group_Description: "",
    Subgroup: "",
    Subgroup_Description: "",
    Option_Type: "",
    Line_Item_Type: "Estimate",
    Description: "1-Drywall Installation (43.67 SF) -5/8 drywall - hung, taped, floated, ready for paint",
    Quantity: 1.0,
    Unit: "",
    Unit_Cost: 393.0,
    Cost_Type: "Subcontractor",
    Marked_As: "",
    Builder_Cost: 393.0,
    Markup: 188.0,
    Markup_Type: "C/P",
    Unit_Price: 581.0,
    Client_Price: 581.0,
    Margin: 32.36,
    Profit: 188.0,
    Percent_Invoiced: 100.0,
    Internal_Notes: "",
    ID_Jobs: "PTL50001",
    ID_Order: "ORD50002",
  },
  {
    ID_EstimateItem: "EST50005",
    Category: "5000 - 5999 Finishing Trades",
    Cost_Code: "5300 - Painting—interior",
    Title: "Painting",
    Parent_Group: "D12 Turnover Items",
    Parent_Group_Description: "",
    Subgroup: "",
    Subgroup_Description: "",
    Option_Type: "",
    Line_Item_Type: "Estimate",
    Description: "Area: Living/Dining/Bedroom/Bathroom. Scope of Work: -Prime all new drywall with appropriate primer.",
    Quantity: 1.0,
    Unit: "",
    Unit_Cost: 360.0,
    Cost_Type: "Subcontractor",
    Marked_As: "",
    Builder_Cost: 360.0,
    Markup: -40.0,
    Markup_Type: "C/P",
    Unit_Price: 320.0,
    Client_Price: 320.0,
    Margin: -12.5,
    Profit: -40.0,
    Percent_Invoiced: 100.0,
    Internal_Notes: "",
    ID_Jobs: "PTL50001",
  },
  {
    ID_EstimateItem: "EST50006",
    Category: "3000 - 3999 Rough Structure",
    Cost_Code: "3610 - HVAC—rough",
    Title: "HVAC Ducts",
    Parent_Group: "D12 HVAC / Water Heater",
    Parent_Group_Description: "",
    Subgroup: "",
    Subgroup_Description: "",
    Option_Type: "",
    Line_Item_Type: "Estimate",
    Description: "Full ductwork install to serve: 2 bedrooms - 1 bathroom - Kitchen - Living/dining area.",
    Quantity: 1.0,
    Unit: "",
    Unit_Cost: 1200.0,
    Cost_Type: "Subcontractor",
    Marked_As: "",
    Builder_Cost: 1200.0,
    Markup: 49.25,
    Markup_Type: "%",
    Unit_Price: 1791.0,
    Client_Price: 1791.0,
    Margin: 33.0,
    Profit: 591.0,
    Percent_Invoiced: 100.0,
    Internal_Notes: "",
    ID_Jobs: "PTL50001",
  },
]

export const mockOrders: SubcontractorOrder[] = [
  {
    ID_Order: "ORD50001",
    Order_Name: "Permit Management Package",
    ID_Subcontractor: "SUBC50001",
    ID_Jobs: "PTL50001",
    Items: mockEstimateItems.filter((item) => item.ID_Order === "ORD50001"),
    Total_Builder_Cost: 800.0,
    Total_Client_Price: 1890.0,
    Total_Profit: 1090.0,
    Created_Date: "2024-01-15",
    Status: "Approved",
  },
  {
    ID_Order: "ORD50002",
    Order_Name: "Interior Finishing Work",
    ID_Subcontractor: "SUBC50002",
    ID_Jobs: "PTL50001",
    Items: mockEstimateItems.filter((item) => item.ID_Order === "ORD50002"),
    Total_Builder_Cost: 473.0,
    Total_Client_Price: 701.0,
    Total_Profit: 228.0,
    Created_Date: "2024-01-20",
    Status: "Approved",
  },
]
