import type { Job } from "@/lib/types"

export const mockJobs: Job[] = [
  {
    id: "QID50001",
    jobType: "QID",
    projectName: "Unit 302 - Bathroom Countertop",
    projectLocation: "123 Main St, Miami, FL",
    status: "Scheduled/Work in progress",
    poWtnWo: "PO-2024-001",
    serviceType: "Cabinets/Countertops",
    dateAssigned: "19/11/2025",
    estimatedStartDate: "25/11/2025",
    estimatedDuration: "2 weeks",
    client: {
      id: "CLI50001",
      name: "Jose Gómez",
      companyName: "Star Holdings Inc.",
      email: "jose.gomez@brightprop.com",
      phone: "+1-305-555-1234",
      address: "123 St, New York, NY 33123",
      avatar: "",
      status: "Active",
    },
    representatives: [],
    createdAt: "2024-11-15",
    pricingData: {
      gqmFormulaPricing: 1273.0,
      gqmAdjFormulaPricing: 1273.0,
      gqmTargetReturn: 30.0,
      gqmTargetSoldPricing: 1654.9,
      gqmPremiumInMoney: 200.0,
      gqmFinalSoldPricing: 1854.9,
      gqmFinalPercentage: 45.7,
      gqmTotalChangeOrders: 0.0,
    },
  },
  {
    id: "QID50002",
    jobType: "QID",
    projectName: "Office Building Restoration",
    projectLocation: "456 Corporate Blvd, Miami, FL",
    status: "Assigned/P.Quote",
    poWtnWo: "PO-2024-002",
    serviceType: "General Contractor",
    dateAssigned: "28/11/2025",
    estimatedStartDate: "05/12/2025",
    estimatedDuration: "4 weeks",
    client: {
      id: "CLI50001",
      name: "Jose Gómez",
      companyName: "Star Holdings Inc.",
      email: "jose.gomez@brightprop.com",
      phone: "+1-305-555-1234",
      address: "123 St, New York, NY 33123",
      avatar: "",
      status: "Active",
    },
    representatives: [],
    createdAt: "2024-11-20",
    pricingData: {
      gqmFormulaPricing: 8500.0,
      gqmAdjFormulaPricing: 8500.0,
      gqmTargetReturn: 28.0,
      gqmTargetSoldPricing: 10880.0,
      gqmPremiumInMoney: 500.0,
      gqmFinalSoldPricing: 11380.0,
      gqmFinalPercentage: 33.9,
      gqmTotalChangeOrders: 0.0,
    },
  },
  {
    id: "PTL50001",
    jobType: "PTL",
    projectName: "Residential Renovation",
    projectLocation: "789 Beach Ave, Miami Beach, FL",
    status: "Scheduled/Work in progress",
    poWtnWo: "PO-2024-003",
    serviceType: "Full Renovation",
    dateAssigned: "15/01/2025",
    estimatedStartDate: "20/01/2025",
    estimatedDuration: "6 weeks",
    client: {
      id: "CLI50002",
      name: "Maria Rodriguez",
      companyName: "Coastal Properties LLC",
      email: "maria.rodriguez@coastal.com",
      phone: "+1-305-555-5678",
      address: "456 Ocean Dr, Miami Beach, FL 33139",
      avatar: "",
      status: "Active",
    },
    representatives: [],
    createdAt: "2025-01-10",
    pricingData: {
      gqmFormulaPricing: 15200.0,
      gqmAdjFormulaPricing: 15200.0,
      gqmTargetReturn: 32.0,
      gqmTargetSoldPricing: 20064.0,
      gqmPremiumInMoney: 800.0,
      gqmFinalSoldPricing: 20864.0,
      gqmFinalPercentage: 37.2,
      gqmTotalChangeOrders: 0.0,
    },
  },
]
