import type { Subcontractor, Technician } from "@/lib/types"

export const mockTechnicians: Technician[] = [
  {
    ID_Technician: "TEC50001",
    Name: "Nicolas Diaz",
    Email: "nicolasdiaz@gmail.com",
    Location: "Miami, Florida",
    Phone_number: "305 831 9210",
    Type: "Worker",
    Formula: 400,
    Adj_Formula: 420,
    ID_Subcontractor: "SUBC50001",
  },
  {
    ID_Technician: "TEC50002",
    Name: "Carlos Rodriguez",
    Email: "carlos.rodriguez@gmail.com",
    Location: "Miami, Florida",
    Phone_number: "305 442 7788",
    Type: "Leader",
    Formula: 600,
    Adj_Formula: 650,
    ID_Subcontractor: "SUBC50001",
  },
  {
    ID_Technician: "TEC50003",
    Name: "Maria Garcia",
    Email: "maria.garcia@gmail.com",
    Location: "Fort Lauderdale, Florida",
    Phone_number: "954 123 4567",
    Type: "Worker",
    Formula: 380,
    Adj_Formula: 400,
    ID_Subcontractor: "SUBC50001",
  },
  {
    ID_Technician: "TEC50004",
    Name: "Juan Martinez",
    Email: "juan.martinez@gmail.com",
    Location: "Miami, Florida",
    Phone_number: "786 555 9876",
    Type: "Leader",
    Formula: 550,
    Adj_Formula: 580,
    ID_Subcontractor: "SUBC50002",
  },
  {
    ID_Technician: "TEC50005",
    Name: "Ana Lopez",
    Email: "ana.lopez@gmail.com",
    Location: "Coral Gables, Florida",
    Phone_number: "305 789 0123",
    Type: "Worker",
    Formula: 420,
    Adj_Formula: 445,
    ID_Subcontractor: "SUBC50002",
  },
]

export const mockSubcontractors: Subcontractor[] = [
  {
    ID_Subcontractor: "SUBC50001",
    Name: "Abel Morgado Diaz",
    Organization: "Spaces LLC",
    Organization_website: "www.spacesllc.com",
    Address: "123 Northwest 47th Avenue, Miami, FL 33126",
    Phone_number: "305 785 3641",
    Email: "spacesllc@gmail.com",
    Score: 200,
    Status: "Active",
    GQM_Compliance: "Active",
    GQM_Best_Service_Training: "Inactive",
    technicians: mockTechnicians.filter((t) => t.ID_Subcontractor === "SUBC50001"),
  },
  {
    ID_Subcontractor: "SUBC50002",
    Name: "Roberto Sanchez",
    Organization: "ProBuild Services",
    Organization_website: "www.probuildservices.com",
    Address: "456 Biscayne Boulevard, Miami, FL 33132",
    Phone_number: "305 234 5678",
    Email: "contact@probuildservices.com",
    Score: 185,
    Status: "Active",
    GQM_Compliance: "Active",
    GQM_Best_Service_Training: "Active",
    technicians: mockTechnicians.filter((t) => t.ID_Subcontractor === "SUBC50002"),
  },
  {
    ID_Subcontractor: "SUBC50003",
    Name: "Linda Fernandez",
    Organization: "Elite Construction",
    Organization_website: "www.eliteconstruction.com",
    Address: "789 Collins Avenue, Miami Beach, FL 33139",
    Phone_number: "305 987 6543",
    Email: "info@eliteconstruction.com",
    Score: 220,
    Status: "Active",
    GQM_Compliance: "Active",
    GQM_Best_Service_Training: "Active",
    technicians: [],
  },
  {
    ID_Subcontractor: "SUBC50004",
    Name: "Miguel Torres",
    Organization: "Precision Builders",
    Organization_website: "www.precisionbuilders.com",
    Address: "321 Coral Way, Coral Gables, FL 33134",
    Phone_number: "305 456 7890",
    Email: "miguel@precisionbuilders.com",
    Score: 165,
    Status: "Inactive",
    GQM_Compliance: "Inactive",
    GQM_Best_Service_Training: "Inactive",
    technicians: [],
  },
  {
    ID_Subcontractor: "SUBC50005",
    Name: "Patricia Williams",
    Organization: "Quality Contractors Inc.",
    Organization_website: "www.qualitycontractors.com",
    Address: "555 Ocean Drive, Miami Beach, FL 33140",
    Phone_number: "305 654 3210",
    Email: "patricia@qualitycontractors.com",
    Score: 195,
    Status: "Active",
    GQM_Compliance: "Inactive",
    GQM_Best_Service_Training: "Active",
    technicians: [],
  },
  {
    ID_Subcontractor: "SUBC50006",
    Name: "James Anderson",
    Organization: "Superior Builders",
    Organization_website: "www.superiorbuilders.com",
    Address: "888 Miracle Mile, Coral Gables, FL 33134",
    Phone_number: "305 777 8899",
    Email: "james@superiorbuilders.com",
    Score: 175,
    Status: "Active",
    GQM_Compliance: "Active",
    GQM_Best_Service_Training: "Inactive",
    technicians: [],
  },
  {
    ID_Subcontractor: "SUBC50007",
    Name: "Sofia Martinez",
    Organization: "Premier Construction Group",
    Organization_website: "www.premierconstructiongroup.com",
    Address: "123 Lincoln Road, Miami Beach, FL 33139",
    Phone_number: "305 888 9900",
    Email: "sofia@premierconstructiongroup.com",
    Score: 210,
    Status: "Active",
    GQM_Compliance: "Active",
    GQM_Best_Service_Training: "Active",
    technicians: [],
  },
  {
    ID_Subcontractor: "SUBC50008",
    Name: "David Johnson",
    Organization: "Reliable Contractors LLC",
    Organization_website: "www.reliablecontractors.com",
    Address: "456 Washington Avenue, Miami Beach, FL 33139",
    Phone_number: "305 999 0011",
    Email: "david@reliablecontractors.com",
    Score: 155,
    Status: "Inactive",
    GQM_Compliance: "Inactive",
    GQM_Best_Service_Training: "Inactive",
    technicians: [],
  },
  {
    ID_Subcontractor: "SUBC50009",
    Name: "Isabella Garcia",
    Organization: "Master Builders Corp",
    Organization_website: "www.masterbuilderscorp.com",
    Address: "789 Flagler Street, Miami, FL 33130",
    Phone_number: "305 111 2233",
    Email: "isabella@masterbuilderscorp.com",
    Score: 190,
    Status: "Active",
    GQM_Compliance: "Active",
    GQM_Best_Service_Training: "Active",
    technicians: [],
  },
  {
    ID_Subcontractor: "SUBC50010",
    Name: "Michael Brown",
    Organization: "Expert Construction Services",
    Organization_website: "www.expertconstruction.com",
    Address: "321 SW 8th Street, Miami, FL 33130",
    Phone_number: "305 222 3344",
    Email: "michael@expertconstruction.com",
    Score: 145,
    Status: "Active",
    GQM_Compliance: "Inactive",
    GQM_Best_Service_Training: "Inactive",
    technicians: [],
  },
]
