import type { Task } from "@/lib/types"

export const mockTasks: Task[] = [
  {
    ID_Task: "TSK50001",
    Title: "Initial Site Inspection",
    Description: "Conduct comprehensive site inspection and document current conditions. Take photos and measurements.",
    Status: "completed",
    Assignment_date: "2024-01-15",
    Completion_date: "2024-01-18",
    ID_Jobs: "PTL50001",
    assignedMembers: [
      {
        id: "MEM50001",
        name: "John Smith",
        email: "john.smith@gqm.com",
        phone: "305-123-4567",
        role: "Project Manager",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    assignedTechnicians: [
      {
        ID_Technician: "TEC50001",
        Name: "Nicolas Diaz",
        Email: "nicolasdiaz@gmail.com",
        Location: "Miami, Florida",
        Phone_number: "305 831 9210",
        Type: "Leader",
        Formula: 400,
        Adj_Formula: 420,
        ID_Subcontractor: "SUBC50001",
      },
    ],
    attachments: [],
  },
  {
    ID_Task: "TSK50002",
    Title: "Prepare Restoration Quote",
    Description: "Create detailed quote including materials, labor, and timeline estimates.",
    Status: "in_process",
    Assignment_date: "2024-01-20",
    Completion_date: null,
    ID_Jobs: "PTL50001",
    assignedMembers: [
      {
        id: "MEM50002",
        name: "Sarah Johnson",
        email: "sarah.johnson@gqm.com",
        phone: "305-234-5678",
        role: "Estimator",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    assignedTechnicians: [],
    attachments: [],
  },
  {
    ID_Task: "TSK50003",
    Title: "Client Approval",
    Description: "Present quote to client and obtain approval for restoration work.",
    Status: "pending",
    Assignment_date: "2024-01-25",
    Completion_date: null,
    ID_Jobs: "PTL50001",
    assignedMembers: [],
    assignedTechnicians: [],
    attachments: [],
  },
  {
    ID_Task: "TSK50004",
    Title: "Water Damage Mitigation",
    Description: "Extract standing water and set up dehumidifiers. Monitor moisture levels daily.",
    Status: "under_review",
    Assignment_date: "2024-01-22",
    Completion_date: null,
    ID_Jobs: "PTL50001",
    assignedMembers: [],
    assignedTechnicians: [
      {
        ID_Technician: "TEC50002",
        Name: "Carlos Rodriguez",
        Email: "carlos.r@gmail.com",
        Location: "Miami, Florida",
        Phone_number: "305 456 7890",
        Type: "Worker",
        Formula: 350,
        Adj_Formula: 365,
        ID_Subcontractor: "SUBC50001",
      },
    ],
    attachments: [],
  },
  {
    ID_Task: "TSK50005",
    Title: "Schedule Subcontractors",
    Description: "Coordinate with all subcontractors and establish work schedule.",
    Status: "assigned",
    Assignment_date: "2024-01-23",
    Completion_date: null,
    ID_Jobs: "PTL50001",
    assignedMembers: [
      {
        id: "MEM50001",
        name: "John Smith",
        email: "john.smith@gqm.com",
        phone: "305-123-4567",
        role: "Project Manager",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    assignedTechnicians: [],
    attachments: [],
  },
  {
    ID_Task: "TSK50006",
    Title: "Final Documentation",
    Description: "Compile all project documentation, photos, and completion certificates.",
    Status: "pending",
    Assignment_date: "2024-02-01",
    Completion_date: null,
    ID_Jobs: "PTL50001",
    assignedMembers: [],
    assignedTechnicians: [],
    attachments: [],
  },
]
