import type { Technician } from "@/lib/types"

export const mockTechnicians: Technician[] = [
  {
    ID_Technician: "TECH50001",
    Name: "Maria Rodriguez",
    Email: "maria.rodriguez@spacesllc.com",
    Location: "Miami, FL",
    Phone_number: "+1-305-555-0101",
    Type: "Leader",
    ID_Subcontractor: "SUBC50001",
    Password: "Password123", // In production, this would be hashed
    Avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    ID_Technician: "TECH50002",
    Name: "Carlos Mendez",
    Email: "carlos.mendez@spacesllc.com",
    Location: "Miami, FL",
    Phone_number: "+1-305-555-0102",
    Type: "Worker",
    ID_Subcontractor: "SUBC50001",
    Password: "Worker456",
    Avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    ID_Technician: "TECH50003",
    Name: "Ana Silva",
    Email: "ana.silva@spacesllc.com",
    Location: "Miami, FL",
    Phone_number: "+1-305-555-0103",
    Type: "Worker",
    ID_Subcontractor: "SUBC50001",
    Password: "Technician789",
    Avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    ID_Technician: "TECH50004",
    Name: "Roberto Martinez",
    Email: "roberto.martinez@probuild.com",
    Location: "Fort Lauderdale, FL",
    Phone_number: "+1-954-555-0201",
    Type: "Leader",
    ID_Subcontractor: "SUBC50002",
    Password: "Leader2024",
    Avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    ID_Technician: "TECH50005",
    Name: "Sofia Gonzalez",
    Email: "sofia.gonzalez@probuild.com",
    Location: "Fort Lauderdale, FL",
    Phone_number: "+1-954-555-0202",
    Type: "Worker",
    ID_Subcontractor: "SUBC50002",
    Password: "Sofia123",
    Avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    ID_Technician: "TECH50006",
    Name: "Diego Lopez",
    Email: "diego.lopez@probuild.com",
    Location: "Fort Lauderdale, FL",
    Phone_number: "+1-954-555-0203",
    Type: "Worker",
    ID_Subcontractor: "SUBC50002",
    Password: "Diego456",
    Avatar: "/placeholder.svg?height=100&width=100",
  },
  {
    ID_Technician: "TECH50007",
    Name: "Isabella Torres",
    Email: "isabella.torres@probuild.com",
    Location: "Fort Lauderdale, FL",
    Phone_number: "+1-954-555-0204",
    Type: "Worker",
    ID_Subcontractor: "SUBC50002",
    Password: "Bella789",
    Avatar: "/placeholder.svg?height=100&width=100",
  },
]
